/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicClickRouteImport } from './routes/api/public/click'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicStatsRouteImport } from './routes/api/public/stats'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClickRoute = ApiPublicClickRouteImport.update({
  id: '/api/public/click',
  path: '/api/public/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatsRoute = ApiPublicStatsRouteImport.update({
  id: '/api/public/stats',
  path: '/api/public/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/click': typeof ApiPublicClickRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/click': typeof ApiPublicClickRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/click': typeof ApiPublicClickRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/stats': typeof ApiPublicStatsRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/click'
    | '/api/public/health'
    | '/api/public/stats'
    | '/api/public/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/click'
    | '/api/public/health'
    | '/api/public/stats'
    | '/api/public/waitlist'
  id:
    | '__root__'
    | '/'
    | '/api/public/click'
    | '/api/public/health'
    | '/api/public/stats'
    | '/api/public/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicClickRoute: typeof ApiPublicClickRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicStatsRoute: typeof ApiPublicStatsRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/click': {
      id: '/api/public/click'
      path: '/api/public/click'
      fullPath: '/api/public/click'
      preLoaderRoute: typeof ApiPublicClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats': {
      id: '/api/public/stats'
      path: '/api/public/stats'
      fullPath: '/api/public/stats'
      preLoaderRoute: typeof ApiPublicStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicClickRoute: ApiPublicClickRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicStatsRoute: ApiPublicStatsRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
